### ISSUE TITLE
Cannot cache a existing cahced page

### ISSUE THREAD

**Issue by jasongrishkoff** [arunoda/hello-react-meteor#13]
Hi there, am encountering the below issue fairly frequently.

W20151210-14:47:02.505(2)? (STDERR) Error: Cannot cache a existing cahced page: /
W20151210-14:47:02.505(2)? (STDERR) at class.cachePage (server/route.js:164:13)
W20151210-14:47:02.505(2)? (STDERR) at ServerResponse._injectHtml.res.write (server/route.js:86:16)
W20151210-14:47:02.506(2)? (STDERR) at Object.handle (packages/webapp/webapp_server.js:717:1)
W20151210-14:47:02.506(2)? (STDERR) at next (/root/.meteor/packages/webapp/.1.2.3.1r2qb00++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
W20151210-14:47:02.506(2)? (STDERR) at next (/root/.meteor/packages/webapp/.1.2.3.1r2qb00++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:192:9)
W20151210-14:47:02.506(2)? (STDERR) at next (/root/.meteor/packages/webapp/.1.2.3.1r2qb00++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:127:23)
W20151210-14:47:02.507(2)? (STDERR) at middleware (packages/oauth/oauth_server.js:157:1)
W20151210-14:47:02.507(2)? (STDERR) at packages/oauth/oauth_server.js:146:1

**Comment by sahanDissanayake** [comment]
Yes, I got this issue too.. and on browser get the error `Uncaught error`

**Comment by arunoda** [comment]
Thanks. Let me see it.

**Comment by sahanDissanayake** [comment]
One way I get the issue is when, I have the app open on dev mode in different browsers.. 

App works fine in one browser but not in the other, I get this error on the other browser

**Comment by jasongrishkoff** [comment]
Another potentially related error is that if I open an incognito, it's initial render is of the view that I had as a logged-in user -- clearly something cached.

**Comment by sahanDissanayake** [comment]
I think it is something to do with cookie tossing

```
Uncaught Error: seems like cookie tossing is happening. visit here: http://git.io/q4IRHQ
react-runtime-dev.js:1697 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) d=".1x6d8ng7nr4.1"><div data-reactid=".1
 (server) d=".1x6d8ng7nr4.1"><h3 data-reactid=".1x
```

**Comment by arunoda** [comment]
Guys, check now.
We've already enabled caching for SSR by default. I turned off it with the
new version.

Let me know, how it works.

**Comment by jasongrishkoff** [comment]
Great, updating and will let you know how it goes!

On Fri, Dec 11, 2015 at 11:04 AM, Arunoda Susiripala <
notifications@github.com> wrote:

> Guys, check now.
> We've already enabled caching for SSR by default. I turned off it with the
> new version.
> 
> Let me know, how it works.
> 
> On Fri, Dec 11, 2015 at 1:52 PM sahanDissanayake <notifications@github.com
> 
> > wrote:
> > 
> > I think it is something to do with cookietossing
> > 
> > Uncaught Error: seems like cookie tossing is happening. visit here:
> > http://git.io/q4IRHQ
> > react-runtime-dev.js:1697 http://git.io/q4IRHQreact-runtime-dev.js:1697
> > Warning: React attempted to reuse markup in a container but the checksum
> > was invalid. This generally means that you are using server rendering and
> > the markup generated on the server was not what the client was expecting.
> > React injected new markup to compensate which works but you have lost many
> > of the benefits of server rendering. Instead, figure out why the markup
> > being generated is different on the client or server:
> > (client) d=".1x6d8ng7nr4.1"><div data-reactid=".1
> > (server) d=".1x6d8ng7nr4.1"><h3 data-reactid=".1x
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/arunoda/hello-react-meteor/issues/13#issuecomment-163872632
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/arunoda/hello-react-meteor/issues/13#issuecomment-163880374
> .

## 

Jason Grishkoff

## Founder, Indie Shuffle

website: indieshuffle.com http://www.indieshuffle.com/
twitter: @indieshuffle http://www.twitter.com/indieshuffle
facebook: facebook.com/indieshuffle http://www.facebook.com/indieshuffle

**Comment by sahanDissanayake** [comment]
Arunoda, Lets say caching is turned off, is this only going to make CPU usage more intense ? https://twitter.com/kadirahq/status/620467416749838336

**Comment by arunoda** [comment]
Yes.
