### ISSUE TITLE
render a page after subscription is ready 

### ISSUE THREAD

**Issue by alexedev** [arunoda/hello-react-meteor#3]
What is the best way to check if subscription is ready before rendering a component? 
I know that FlowRouter.subsReady() is used for this but do not understand where to do checking exactly in jsx or in routes and how.

**Comment by alexedev** [comment]
This is a reimplementation of the case https://github.com/arunoda/hello-react-meteor/compare/master...buduguru:master

So, in your original code on "/" route we subscribe to all the posts ("posts" subscription) and then if we click on a post title it opens OK because it gets data from the ''posts" subscription first and only then gets it from 'singlePost'(so it is not important to be ready for the post to be loaded). But If we do not subscribe to "posts" and try to open a post by clicking a explicitly added link (I added it in menu, see the code) then it is not loaded because 'singlePost' subscription for that post is not ready yet.

So we get these two errors in chrome console:
1. this one says that we do not get data yet 

```
Exception from Tracker recompute function: debug.js:41
TypeError: Cannot read property 'title' of undefined
    at React.createClass.render (http://localhost:3000/both/components/post_page.jsx.js?1d10c2e40b61df0590cb425b179df98b6f26ce3a:22:23)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:7398:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:7425:14)
    at wrapper [as _renderValidatedComponent] (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:13974:21)
    at ReactCompositeComponentMixin.mountComponent (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:6846:30)
    at wrapper [as mountComponent] (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:13974:21)
    at Object.ReactReconciler.mountComponent (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:14791:35)
    at ReactDOMComponent.ReactMultiChild.Mixin._mountChildByNameAtIndex (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:13652:40)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:13558:16)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:13503:14) debug.js:41
```
1. but after subscription is ready Tracker gets it but React cannot re-render the post:

```
Exception from Tracker recompute function: debug.js:41
TypeError: Cannot read property '_currentElement' of null
    at ReactCompositeComponentMixin._updateRenderedComponent (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:7353:52)
    at ReactCompositeComponentMixin._performComponentUpdate (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:7335:10)
    at ReactCompositeComponentMixin.updateComponent (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:7251:12)
    at wrapper [as updateComponent] (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:13974:21)
    at ReactCompositeComponentMixin.performUpdateIfNecessary (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:7148:12)
    at Object.ReactReconciler.performUpdateIfNecessary (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:14868:22)
    at runBatchedUpdates (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:16693:21)
    at ReactReconcileTransaction.Mixin.perform (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:18637:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:18637:20)
    at ReactUpdatesFlushTransaction.assign.perform (http://localhost:3000/packages/react-runtime-dev.js?a5361e646c47aa55f963e236a8bfe948c401c5bd:16637:38) debug.js:41
```

So it seems that we need to be presubscribed to any post before opening it, right? Or is it possible to render a component only after the subscription for a singlePost is ready? Is it ok to wait for a subscription in case of SSR?

**Comment by alexedev** [comment]
If we implement subscription and wait for them in postPage component exactly as described here https://kadira.io/academy/meteor-routing-guide/content/subscriptions-and-data-management/with-react then everything works as expected on a client but not on a server:

if we reload http://localhost:3000/post/one page, then only "Unexpected error." text is rendered and in server console we get an error:

```
W20150729-16:46:28.451(2)? (STDERR) /home/bg/.meteor/packages/meteor-tool/.1.1.3.d1sfvj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150729-16:46:28.452(2)? (STDERR)                                             throw(ex);
W20150729-16:46:28.454(2)? (STDERR)                                                   ^
W20150729-16:46:28.456(2)? (STDERR) Error: Can't call yield in a noYieldsAllowed block!
W20150729-16:46:28.457(2)? (STDERR)     at Function.Fiber.yield (packages/meteor/fiber_helpers.js:8:1)
W20150729-16:46:28.457(2)? (STDERR)     at Function.wait (/home/bg/.meteor/packages/meteor-tool/.1.1.3.d1sfvj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:183:14)
W20150729-16:46:28.457(2)? (STDERR)     at Object.Future.wait (/home/bg/.meteor/packages/meteor-tool/.1.1.3.d1sfvj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:397:10)
W20150729-16:46:28.457(2)? (STDERR)     at [object Object]._.extend._nextObject (packages/mongo/mongo_driver.js:929:1)
W20150729-16:46:28.457(2)? (STDERR)     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:963:1)
W20150729-16:46:28.457(2)? (STDERR)     at [object Object]._.extend.map (packages/mongo/mongo_driver.js:973:1)
W20150729-16:46:28.458(2)? (STDERR)     at [object Object]._.extend.fetch (packages/mongo/mongo_driver.js:997:1)
W20150729-16:46:28.458(2)? (STDERR)     at [object Object].Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:812:1)
W20150729-16:46:28.458(2)? (STDERR)     at packages/meteorhacks:flow-router-ssr/server/ssr_context.js:41:1
W20150729-16:46:28.458(2)? (STDERR)     at Array.forEach (native)
=> Exited with code: 8

```

**Comment by arunoda** [comment]
Hmm. Okay let's see. I'll add it the current version. 
Then we can see that.

**Comment by arunoda** [comment]
I've updated the code of this repo with the new style. Check that out.

**Comment by alexedev** [comment]
It seems to work properly now. Thank you!
